### ISSUE TITLE
Compilation warnings upon app start

### ISSUE THREAD

**Issue by sdornan** [Chevtek/angular-spinners#30]
I'm getting two warnings when starting an `angular-cli` app using the newest version of `angular` (5.0.5):
```
WARNING in ./node_modules/@chevtek/angular-spinners/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compiler.js:506:17)
    at /Users/sdornan/Code/search-compare-ng2/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/@chevtek/angular-spinners/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/@chevtek/angular-spinners/dist/src/spinner.module.js
 @ ./node_modules/@chevtek/angular-spinners/dist/src/index.js
 @ ./node_modules/@chevtek/angular-spinners/dist/index.js
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/@chevtek/angular-spinners/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compiler.js:506:17)
    at /Users/sdornan/Code/search-compare-ng2/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/Users/sdornan/Code/search-compare-ng2/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/@chevtek/angular-spinners/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/@chevtek/angular-spinners/dist/src/spinner.module.js
 @ ./node_modules/@chevtek/angular-spinners/dist/src/index.js
 @ ./node_modules/@chevtek/angular-spinners/dist/index.js
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Compiled with warnings.
```

**Comment by mariusl-a** [comment]
+1

**Comment by DanGlass** [comment]
+1

**Comment by Josh-Kirk** [comment]
+ 1

**Comment by nwallman** [comment]
+1

**Comment by dcods22** [comment]
+1

**Comment by oliveringham** [comment]
+1

**Comment by MariusRettler** [comment]
I have the same problem.
A temporary fix for me is, deleting the node_modules folder in the angular-spinners module.
But this is just a temporary fix for me, because when have a build chain or something else, it is very hacky to modify the build scripts to delete this folder.
For creating the build i use:
angular/cli: 1.6.5
angular 5.2.1
Node v9.4.0

**Comment by frdrcklopez** [comment]
+1

**Comment by MariusRettler** [comment]
So i solved the problem by replacing this dependency with a fork of this project.
I used this updated fork: https://github.com/JoeSong/angular-spinners
Just do:
npm install --save https://github.com/JoeSong/angular-spinners/master

maybe remove the node_modules folder and the package-lock.json first, then update the dependency and do an npm install. After that the warnings should be gone.
